export const userAvatar = [
    "Maria",
    "Vivian",
    "Alexander",
    "Adrian",
    "Jameson",
    "Mackenzie",
    "Aidan",
    "Wyatt",
    "George",
    "Caleb",
    "Ryan",
    "Aiden",
    "Brooklynn",
    "Chase",
    "Luis",
]